echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER  >> .env

echo VPS_IP_ADDRESS=$VPS_IP_ADDRESS >> .env
echo VPS_USER=$VPS_USER >> .env
echo API_IMAGE=$IMAGE:api  >> .env


echo ENVIRONMENT=$ENVIRONMENT >> .env
echo TITLE=$TITLE >> .env
echo CLIENT_ROOT_PATH=$CLIENT_ROOT_PATH >> .env
echo ADMIN_ROOT_PATH=$ADMIN_ROOT_PATH >> .env
echo CLIENT_URL=$CLIENT_URL >> .env
echo API_BASE_URL=$API_BASE_URL >> .env
echo API_URL=$API_URL >> .env
echo ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES >> .env
# POSTGRES

echo POSTGRES_HOST=$POSTGRES_HOST >> .env
echo POSTGRES_PORT=$POSTGRES_PORT >> .env
echo POSTGRES_USER=$POSTGRES_USER >> .env
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
# Redis
echo REDIS_HOST=$REDIS_HOST >> .env
echo REDIS_PORT=$REDIS_PORT >> .env
echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env
echo REDIS_DATABASE=$REDIS_DATABASE >> .env
# Token
echo TOKEN_SECRET_KEY=$TOKEN_SECRET_KEY >> .env
# Opera Log
echo OPERA_LOG_ENCRYPT_SECRET_KEY=$OPERA_LOG_ENCRYPT_SECRET_KEY >> .env
# Admin
# OAuth2
echo OAUTH2_GITHUB_CLIENT_ID=$OAUTH2_GITHUB_CLIENT_ID >> .env
echo OAUTH2_GITHUB_CLIENT_SECRET=$OAUTH2_GITHUB_CLIENT_SECRET >> .env
echo OAUTH2_LINUX_DO_CLIENT_ID=$OAUTH2_LINUX_DO_CLIENT_ID >> .env
echo OAUTH2_LINUX_DO_CLIENT_SECRET=$OAUTH2_LINUX_DO_CLIENT_SECRET >> .env
# Task
# Celery
echo CELERY_BROKER_REDIS_DATABASE=$CELERY_BROKER_REDIS_DATABASE >> .env
echo CELERY_BACKEND_REDIS_DATABASE=$CELERY_BACKEND_REDIS_DATABASE >> .env
# Rabbitmq
echo RABBITMQ_HOST=$RABBITMQ_HOST >> .env
echo RABBITMQ_PORT=$RABBITMQ_PORT >> .env
echo RABBITMQ_USERNAME=$RABBITMQ_USERNAME >> .env
echo RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD >> .env
# Minio
echo MINIO_ENDPOINT=$MINIO_ENDPOINT >> .env
echo MINIO_PORT=$MINIO_PORT >> .env
echo MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY >> .env
echo MINIO_SECRET_KEY=$MINIO_SECRET_KEY >> .env
echo MINIO_BUCKET_NAME=$MINIO_BUCKET_NAME >> .env
echo MINIO_CLOUD_URL=$MINIO_CLOUD_URL >> .env

echo SMTP_TLS=$SMTP_TLS  >> .env
echo SMTP_PORT=$SMTP_PORT  >> .env
echo SMTP_HOST=$SMTP_HOST  >> .env
echo SMTP_USER=$SMTP_USER  >> .env
echo EMAILS_FROM_EMAIL=$EMAILS_FROM_EMAIL  >> .env
echo EMAILS_FROM_NAME=$EMAILS_FROM_NAME  >> .env
echo SMTP_PASSWORD=$SMTP_PASSWORD  >> .env