from pydantic import BaseModel, ConfigDict, EmailStr, validate_email

# Custom validation error messages without validation expected content (i.e., input content).
# The supported expected content fields can be found at the link below:
# https://github.com/pydantic/pydantic-core/blob/a5cb7382643415b716b1a7a5392914e50f726528/tests/test_errors.py#L266
# To replace the expected content fields, refer to the link below:
# https://github.com/pydantic/pydantic/blob/caa78016433ec9b16a973f92f187a7b6bfde6cb5/docs/errors/errors.md?plain=1#L232
CUSTOM_VALIDATION_ERROR_MESSAGES = {
    'arguments_type': 'Incorrect argument type input',
    'assertion_error': 'Assertion execution error',
    'bool_parsing': 'Boolean value parsing error',
    'bool_type': 'Boolean type input error',
    'bytes_too_long': 'Byte length input is too long',
    'bytes_too_short': 'Byte length input is too short',
    'bytes_type': 'Byte type input error',
    'callable_type': 'Callable object type input error',
    'dataclass_exact_type': 'Dataclass instance type input error',
    'dataclass_type': 'Dataclass type input error',
    'date_from_datetime_inexact': 'Non-zero date component input',
    'date_from_datetime_parsing': 'Date input parsing error',
    'date_future': 'Date input is not in the future',
    'date_parsing': 'Date input validation error',
    'date_past': 'Date input is not in the past',
    'date_type': 'Date type input error',
    'datetime_future': 'Datetime input is not in the future',
    'datetime_object_invalid': 'Invalid datetime object input',
    'datetime_parsing': 'Datetime input parsing error',
    'datetime_past': 'Datetime input is not in the past',
    'datetime_type': 'Datetime type input error',
    'decimal_max_digits': 'Too many decimal places input',
    'decimal_max_places': 'Incorrect decimal places input',
    'decimal_parsing': 'Decimal input parsing error',
    'decimal_type': 'Decimal type input error',
    'decimal_whole_digits': 'Incorrect decimal places input',
    'dict_type': 'Dictionary type input error',
    'enum': 'Enum member input error, allowed {expected}',
    'extra_forbidden': 'Extra field input is forbidden',
    'finite_number': 'Finite number input error',
    'float_parsing': 'Float input parsing error',
    'float_type': 'Float type input error',
    'frozen_field': 'Frozen field input error',
    'frozen_instance': 'Modification of frozen instance is forbidden',
    'frozen_set_type': 'Frozen type input is forbidden',
    'get_attribute_error': 'Error retrieving attribute',
    'greater_than': 'Input value is too large',
    'greater_than_equal': 'Input value is too large or equal',
    'int_from_float': 'Integer type input error',
    'int_parsing': 'Integer input parsing error',
    'int_parsing_size': 'Integer input parsing size error',
    'int_type': 'Integer type input error',
    'invalid_key': 'Invalid key input',
    'is_instance_of': 'Instance type input error',
    'is_subclass_of': 'Subclass type input error',
    'iterable_type': 'Iterable type input error',
    'iteration_error': 'Iteration value input error',
    'json_invalid': 'Invalid JSON string input',
    'json_type': 'JSON type input error',
    'less_than': 'Input value is too small',
    'less_than_equal': 'Input value is too small or equal',
    'list_type': 'List type input error',
    'literal_error': 'Literal value input error',
    'mapping_type': 'Mapping type input error',
    'missing': 'Missing required field',
    'missing_argument': 'Missing argument',
    'missing_keyword_only_argument': 'Missing keyword-only argument',
    'missing_positional_only_argument': 'Missing positional-only argument',
    'model_attributes_type': 'Model attributes type input error',
    'model_type': 'Model instance input error',
    'multiple_argument_values': 'Too many argument values input',
    'multiple_of': 'Input value is not a multiple',
    'no_such_attribute': 'Invalid attribute assignment',
    'none_required': 'Input value must be None',
    'recursion_loop': 'Input recursion loop',
    'set_type': 'Set type input error',
    'string_pattern_mismatch': 'String pattern input mismatch',
    'string_sub_type': 'String subtype input error',
    'string_too_long': 'String input is too long',
    'string_too_short': 'String input is too short',
    'string_type': 'String type input error',
    'string_unicode': 'String input is not Unicode',
    'time_delta_parsing': 'Timedelta input parsing error',
    'time_delta_type': 'Timedelta type input error',
    'time_parsing': 'Time input parsing error',
    'time_type': 'Time type input error',
    'timezone_aware': 'Missing timezone input information',
    'timezone_naive': 'Timezone input information is forbidden',
    'too_long': 'Input is too long',
    'too_short': 'Input is too short',
    'tuple_type': 'Tuple type input error',
    'unexpected_keyword_argument': 'Unexpected keyword argument input',
    'unexpected_positional_argument': 'Unexpected positional argument input',
    'union_tag_invalid': 'Union tag input error',
    'union_tag_not_found': 'Union tag input not found',
    'url_parsing': 'URL input parsing error',
    'url_scheme': 'URL input scheme error',
    'url_syntax_violation': 'URL input syntax violation',
    'url_too_long': 'URL input is too long',
    'url_type': 'URL type input error',
    'uuid_parsing': 'UUID input parsing error',
    'uuid_type': 'UUID type input error',
    'uuid_version': 'UUID version type input error',
    'value_error': 'Value input error',
}

CUSTOM_USAGE_ERROR_MESSAGES = {
    'class-not-fully-defined': 'Class property type is not fully defined',
    'custom-json-schema': '__modify_schema__ method has been deprecated in V2',
    'decorator-missing-field': 'Invalid field validator defined',
    'discriminator-no-field': 'Discriminator field not fully defined',
    'discriminator-alias-type': 'Discriminator field uses non-string type definition',
    'discriminator-needs-literal': 'Discriminator field needs to use literal definition',
    'discriminator-alias': 'Discriminator field alias definition inconsistency',
    'discriminator-validator': 'Discriminator field cannot define field validators',
    'model-field-overridden': 'Field without type definition cannot be overridden',
    'model-field-missing-annotation': 'Field type definition is missing',
    'config-both': 'Duplicate configuration item definition',
    'removed-kwargs': 'Call to removed keyword configuration parameters',
    'invalid-for-json-schema': 'Invalid JSON type present',
    'base-model-instantiated': 'Instantiation of base model is forbidden',
    'undefined-annotation': 'Type definition is missing',
    'schema-for-unknown-type': 'Unknown type definition',
    'create-model-field-definitions': 'Field definition error',
    'create-model-config-base': 'Configuration item definition error',
    'validator-no-fields': 'Field validator did not specify fields',
    'validator-invalid-fields': 'Field validator fields definition error',
    'validator-instance-method': 'Field validator must be a class method',
    'model-serializer-instance-method': 'Serializer must be an instance method',
    'validator-v1-signature': 'V1 field validator signature has been deprecated',
    'validator-signature': 'Field validator signature error',
    'field-serializer-signature': 'Field serializer signature unrecognized',
    'model-serializer-signature': 'Model serializer signature unrecognized',
    'multiple-field-serializers': 'Multiple field serializers defined',
    'invalid_annotated_type': 'Invalid type definition',
    'type-adapter-config-unused': 'Type adapter configuration item definition error',
    'root-model-extra': 'Root model cannot define extra fields',
}

class CustomEmailStr(EmailStr):
    @classmethod
    def _validate(cls, __input_value: str) -> str:
        return None if __input_value == '' else validate_email(__input_value)[1]

class SchemaBase(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
